version: '3.9'
services:
  
  freezer-app-db:
    image: postgres
    env_file:
      - ./freezer-app-backend/docker.env
    ports:
      - '5432:5432'
#    volumes:
#      - freezer-app-postgres:/var/lib/postgresql/data
  freezer-app-backend:
    build: ./freezer-app-backend
    env_file:
      - ./freezer-app-backend/.env
    ports:
      - '3000:3000'
    depends_on:
      - freezer-app-db
  freezer-app-frontend:
    build: ./freezer-app-frontend
    ports:
      - '4200:4200'